### ISSUE TITLE
Estado incorrecto Containers "creados"

### ISSUE THREAD

**Issue by garanda21** [dgongut/docker-controller-bot#1]
Para los contenedores que fueron creados pero no iniciados, el listado muestra un estado incorrecto, los muestras en verde 🟢 como si se estuvieran ejecutando. 

![image](https://github.com/dgongut/docker-controller-bot/assets/9530250/78ef5109-5f5d-4aff-aeb0-9f4e623a89c3)

Pero estos contenedores solamente fueron creados sin ejecutarlos:

![image](https://github.com/dgongut/docker-controller-bot/assets/9530250/6b398849-1f66-4983-ba03-80defcc96544)

Para tu referencia, te dejo la salida del comando `docker ps -a`:

![image](https://github.com/dgongut/docker-controller-bot/assets/9530250/a1114a83-9bdd-40a0-bc4f-2c4dc41b6a8a)

**Comment by dgongut** [comment]
Error identificado. Se corregirá en la próxima versión dentro de unos días. 👍🏻

**Comment by dgongut** [comment]
Corregido en la versión v1.1.0

Se ha añadido la detección de la creación de un contenedor así como el resto de estados posibles a los flujos.
