### ISSUE TITLE
Request: manual update command

### ISSUE THREAD

**Issue by ManCaveMedia** [dgongut/docker-controller-bot#10]
I turned off the automated update check, because I have a watchtower container that updates my containers at specific times.
However, I would like to be able to use Docker Controller Bot to update specific containers manually.

/update -> ask what container to check updates for
[select container]
And then follow the existing update logic for the selected container...

**Comment by dgongut** [comment]
This is a very good idea and will be included in future versions. Along with the ability to select a different tag available for the same image and architecture.

**Comment by dgongut** [comment]
Done in v2.1.0

**Comment by ManCaveMedia** [comment]
The manual update works.
Thanks for that.

However, I imagined it would check for updates first and then ask if you want to install the update, if available.

Without the auto update check active you're updating without knowing which update or whether there even is an update available.

**Comment by dgongut** [comment]
Yeah! I plan to check the updates before making the update in a future version 👌🏻
