### ISSUE TITLE
Ignore some containers

### ISSUE THREAD

**Issue by dgongut** [dgongut/docker-controller-bot#11]
Add the possibility to set a list of containers to ignore their status changes and updates. Probably with labels on each of those containers instead of specifying a list in the bot.

**Problems**: Right now the detection of when to start/stop/create a container is done centrally. If they are ignored there we won't be notified when we do a /run, /stop.... command either. We would have to send a notification manually if we decide to run any command for those ignored containers.

**Comment by dgongut** [comment]
Partially done in v2.2.1 with `DCB-Ignore-Check-Updates` label

**Comment by jmlv5** [comment]
Sería ideal separar ambos conceptos ignorar "status" y "updates", por ejemplo tengo un contenedor bw-export, que me interesa actualizarlo, pero no que me avise cada día que se ha encendido y apagado.

**Comment by jmlv5** [comment]
Se podría ignorar lo de ignorar estado, cuando se ejecute manualmente un /run y un /stop? Claro en estos casos, que lo lanzas a mano, si que te interesa el feedback...

**Comment by dgongut** [comment]
Eso es lo que me frena ahora mismo. Parece un cambio sencillo, pero estaria duplicando codigo ya que tendria que avisar manualmente si el contenedor tiene eso puesto... lo valorare.

**Comment by dgongut** [comment]
Añadido en la v2.3.0.

Label: DCB-Ignore-Status
