### ISSUE TITLE
Should I remove "created" notification?

### ISSUE THREAD

**Issue by dgongut** [dgongut/docker-controller-bot#13]
After a few weeks of use I feel that message is a bit spammy.

I'm thinking of deleting it and just leaving Initiated/Stopped.

"🔵 El contenedor peticiones-mariadb se ha creado"

**Comment by ManCaveMedia** [comment]
Yeah, it doesn't really add anything...

**Comment by dgongut** [comment]
Finally It was suppressed behind "EXTENDED_MESSAGES" variable
