### ISSUE TITLE
Create some documentation about how to run it locally

### ISSUE THREAD

**Issue by lluisd** [dgongut/docker-controller-bot#14]
I would suggest to have some part about how to run this project locally and the requirements (like Python 2.x) . I am not used to work with Python/dockers to give an example, but for example in node.js will be like explaining these points:

- requires nodejs 20.x installed
- create an .env file in the root of the project with at least the required environment variables.
- have docker running with at least 1 container to test. 
- run it from the root of the project with that command: node app.js

**Comment by dgongut** [comment]
Yeah! I will publish all the needed data to run it locally (via docker)

**Comment by dgongut** [comment]
Done in v2.1.0 [README.md](https://github.com/dgongut/docker-controller-bot/blob/85f9bf9bfc5d59e9f9bbe7b4dd6d5d5d8024a778/README.md)
