### ISSUE TITLE
Actualizaciones contenedores

### ISSUE THREAD

**Issue by taimadoCE** [dgongut/docker-controller-bot#2]
¿Habría alguna posibilidad de inhabilitar las actualizaciones de los contenedores? En algunos casos no se desea que por un motivo u otro uno o varios contenedores se actualicen y entiendo que sería una buena implementación bien poder inhabilitar dichas actualizaciones o también decidir cuales se desea actualizar y cuales no, al estilo de watchtower.

No obstante gracias por el estupendo trabajo hecho.

**Comment by dgongut** [comment]
Por el momento, en la próxima actualización, habrá una función para desactivar el motor de las actualizaciones. Será un todo o nada 👍🏻

**Comment by dgongut** [comment]
Corregido en la versión v1.1.0
Puedes inhabilitar las actualizaciones estableciendo la variable `CHECK_UPDATES=0` en el docker-compose.
