### ISSUE TITLE
Maestro de los Updates

### ISSUE THREAD

**Issue by jmlv5** [dgongut/docker-controller-bot#21]
Ahora mismo si entiendo bien la aplicación, siempre que encuentra una actualización de algún docker te avisa y tienes que actualizar a mano.
Ya he visto que estás trabajando en una forma de evitar avisar sobre la actualización de ciertos contenedores, la propuesta sería:

Poder marcar contenedores para que SIEMPRE se actualicen, simplemente que avise de que lo ha hecho

**Comment by dgongut** [comment]
No es mala idea, añadir una label para la autoactualizacion, ademas de ser relativamente sencillo de implementar. :+1:

**Comment by dgongut** [comment]
Añadido en la v2.3.0.

Label: DCB-Auto-Update
