### ISSUE TITLE
(v2.3.0) No notifica la puesta en marcha de los contenedores

### ISSUE THREAD

**Issue by yeraycito** [dgongut/docker-controller-bot#23]
Antes funcionaba bien pero en la última versión ha dejado de notificar cuando se inicia o detiene un contenedor, en mi caso tengo un script en el nas unido a un cron que inicia y detiene un contenedor a ciertas horas y el bot ha dejado de notificarlo.

Lo mismo ocurre cuando se actualiza un contenedor desde el bot:

<img width="492" alt="Captura" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/dac0a934-e08e-48c0-aae8-924a4df978a2">

Fíjate en lo que aparece el 14 de abril, notifica que se ha detenido y que se ha actualizado pero no que se ha iniciado. 
Aún así te recuerdo lo del principio, ha dejado de notificar los inicios - detenciones  de los contenedores.

**Comment by yeraycito** [comment]
Para que veas la diferencia con lo que ocurría antes:

<img width="395" alt="Captura2" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/d35da8f4-e264-43c2-b765-3ff34057f8f8">

Esas son las notificaciones que recibía cuando mi script iniciaba - detenía el contenedor, esto ahora no ocurre.

**Comment by dgongut** [comment]
Efectivamente era un bug. Se debería solucionar en la versión que acabo de subir 2.3.1.

Muchas gracias!

**Comment by yeraycito** [comment]
<img width="497" alt="Captura" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/63f76608-a8de-43d1-8a5e-e1d770ee1245">

Solucionado, ya vuelve a notificar el inicio - detención del contenedor, imagino que hará lo mismo cuando se actualice desde el bot algún contenedor aunque tengo que decir que no he tenido ocasión de probar esto último, respecto a esto el problema no estaba en que los contenedores se inicien o detengan despues de actualizarlos sino en las notificaciones correspondientes a través del bot. Muchas gracias por darle solución tan pronto.

**Comment by dgongut** [comment]
Muchas gracias por el feedback! Procedo a cerrar la Issue 👍
