### ISSUE TITLE
Cosas extrañas

### ISSUE THREAD

**Issue by yeraycito** [dgongut/docker-controller-bot#28]
El otro dia te comenté que tengo un script en mi nas de inicio - detención de un contenedor asociado a un cron que lo ejecuta a ciertas horas. Aparte de lo anterior tengo instalado el contenedor Kuma monitoreando Google que me sirve para saber si hay caidas en mi conexión de internet, a la hora de las notificaciones Kuma lo hace a través de un bot de Telegram distinto al tuyo. El inicio - detención del contenedor funciona perfecto y recibo las notificaciones pertinentes a través de tu bot:

<img width="495" alt="1" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/8851273c-4ce7-4c6b-810a-02dc3fd3ad6a">

En la imagen que acabo de poner fíjate en la hora y el minuto en que se detiene el contenedor. Resulta que desde que tengo instalada la versión 2.3.3 de tu bot ocurre esto:

<img width="416" alt="10" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/6b248283-c0e8-4829-b6d1-5b721ea81996">

Y anoche se volvió a repetir:

<img width="419" alt="11" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/a9d810e5-9cf2-4262-bbeb-9c0d5069758e">

No ha habido cambios en la configuración de mi red, ni en el nas, ni en los contenedores estos dias así que el principal sospechoso es tu bot aunque no termino de entender porqué ocurre, en cualquier caso no es grave.

**Comment by dgongut** [comment]
¿Y has mirado en los logs a ver si a esa hora el bot está haciendo algo?

Trato de ver la relación con el bot pero no lo veo. Prueba a detener el bot a ver si sigue pasando 👍🏻

**Comment by yeraycito** [comment]
Ya había mirado los logs de tu contenedor y no hay nada extraño a esas horas, ni a ninguna otra. Coincido contigo es que es difícil encontrar relación pero ocurre como las meigas haberlas haylas, en fin, te he hecho caso y he detenido tu contenedor y lo dejaré así hasta mañana. Como el contenedor cloudflared se detendrá esta noche a las 23 horas y 59 minutos mañana te informo si se produce el error con Google.

**Comment by yeraycito** [comment]
Es difícil de demostrar así que tendrás que confiar en mi, anoche con tu contenedor detenido no hubo caida momentánea de Google a la hora y el minuto en que se detuvo el contenedor cloudflared así que aunque parezca extraño se confirma que el culpable de alguna manera que no alcanzo a entender es tu bot pero por si fuera poco esta mañana ha ocurrido otra cosa que lo confirma y que te paso a explicar. Anoche a las 23 horas y 59 minutos mi contenedor cloudflared se detuvo, un rato más tarde comprobé que no hubo notificación por parte de Kuma de caida de Google así que volví a poner en marcha tu contenedor. Esta mañana he visto que tenía una notificación por parte del bot de la existencia de una actualización de mi contenedor Calibre-web y lo he actualizado:



<img width="488" alt="1" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/c123aa1e-2f07-418f-9ffd-213e3505b888">



En la imagen anterior fíjate en la hora y el minuto en el que se ha producido la actualización desde tu bot:



<img width="490" alt="2" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/bb67aace-45e6-409a-979b-d4b421f5d216">


Como te dije no es que sea nada especiálmente grave ni siquiera molesto pero si llamativo.

**Comment by yeraycito** [comment]
Te paso el log de tu contenedor en el que no se ve nada extraño:



<img width="864" alt="3" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/15893cf8-9b6b-447b-9ac2-0fd071268b2f">

**Comment by yeraycito** [comment]
Te paso también el log de Kuma en el que se puede ver que ayer 20 de abril a las 23 horas y 59 minutos en las que se detiene el contenedor cloudflared y tu contenedor estaba detenido no hubo ningún error con Google, si lo hubo el dia anterior y hoy 21 de abril con la actualización del contenedor calibre-web




<img width="968" alt="4" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/35fc9805-2d8a-4cc2-a2e6-6ee8c02c8cf9">

**Comment by yeraycito** [comment]
Te informo que a pesar de lo anterior reinicié el nas y no se ha vuelto a reproducir el error así que si quieres puedes cerrar el tema, aún así me sigue pareciendo extraño las coincidencias temporales de los errores de Google con el comportamiento del bot algo que ocurrió también en el caso de actualizar contenedores desde el bot. En fin, parece que se ha solucionado sólo.

**Comment by dgongut** [comment]
Correlación no implica causalidad. Sigo pensando que es difícilmente achacable al bot cuando este no estaba haciendo nada en ese momento y siendo de naturalezas tan diferentes ambos programas.

Cierro tal cual me has dicho 👍
