### ISSUE TITLE
Diversos errores ( solucionado )

### ISSUE THREAD

**Issue by yeraycito** [dgongut/docker-controller-bot#3]
Enhorabuena por el mejor nuevo contenedor del último siglo para mi gusto. Te explico varios errores que tiene el contenedor que parece que se mantienen en la nueva versión publicada ayer, el orden temporal de la explicación no va a ser perfecto. Hoy he recibido un mensaje del bot de Telegram con el aviso de la nueva actualización:

![10](https://github.com/dgongut/docker-controller-bot/assets/65027248/dd4eed98-94ec-48f0-ac3e-1911d483bc5b)

Sin embargo tu contenedor se auto-actualizó sólo anoche:

![2](https://github.com/dgongut/docker-controller-bot/assets/65027248/a8db2e02-333c-421d-a1ae-c6858b4b2ad1)

Tu contenedor está funcionando sin embargo la imagen aparece sin uso. En la imagen anterior se puede ver que aparte de la notificación de la actualización de tu contenedor también hay actualizaciones para otros dos contenedores, sin embargo el contenedor Homarr también se auto-actualizó anoche sin mediación mia, te comunico que no tengo instalado watchtower. Si te fijas en la imagen de Portainer la imagen latest de Homarr la marca también como sin uso y no ha eliminado la imagen antigua.
Aunque el contenedor de Homarr se actualizó anoche a esa misma hora he recibido el mensaje de que había nueva actualización como se puede ver en la imagen que puse antes cuando reálmente ya se había auto-actualizado sin mediación mía, lo mismo ocurrió con tu contenedor. Aviso, las horas reflejadas en la imagen de Portainer llevan una hora de retraso con respecto a las del bot de Telegram.

Sin saber todavía todo lo anterior lo que si he hecho hoy es actualizar el contenedor kapitsa ( cloudflared ) y en este caso si lo ha hecho corréctamente aunque sigue sin eliminar la imagen antigua.

![11](https://github.com/dgongut/docker-controller-bot/assets/65027248/c822ed0c-344c-41e0-99c5-82ad3ab41cac)

Para terminar te mando el log actual de tu contenedor, ten en cuenta que lleva una hora de retraso al tener mi Portainer así configurado: 

[_Docker-Controller-Bot_logs.txt](https://github.com/dgongut/docker-controller-bot/files/13964218/_Docker-Controller-Bot_logs.txt)

**Comment by yeraycito** [comment]
Lo de eliminar las imágenes antiguas después de una actualización puede ser más importante de lo que parece, si no se hace de esa manera es muy posible que tu contenedor se lie con las imágenes a la hora de buscar nuevas actualizaciones, eso suponiendo que se arreglara el tema de las imágenes latest que considera sin uso, de hecho lo están, aunque bien es cierto que esto último ocurrió con las dos auto-actualizaciones de anoche. Te acabo de comentar que acabo de recrear tu contenedor y antes de hacerlo he eliminado la imagen nueva latest marcada sin uso y me ha dejado sin problemas, sin embargo la imagen anterior Portainer no me dejaba eliminarla aunque había parado tu contenedor. Lo que quiero decir con esto es que a pesar de que tu contenedor se había auto-actualizado anoche lo único que había hecho era autodescargarse la nueva imagen pero no se había autoactualizado así que perdón por mi comentario anterior, lo mismo ocurrió anoche con el contenedor homarr. Resumiendo, parece que tu contenedor busca actualizaciones de los contenedores y si existen las descarga sin preguntar pero no las instala, una vez descargadas las comunica al bot de Telegram.

**Comment by yeraycito** [comment]
Vale, me acabo de fijar que lo de eliminar las imagenes antiguas después de actualizar ya está implementado en la nueva actualización...... hoy no doy una así que perdón otra vez.

**Comment by dgongut** [comment]
Muy buenas @yeraycito! Primeramente muchas gracias por tus comentarios e inquietudes pues, efectivamente, estabas experimentando un bug de la primera versión 1.0.0

En el primer mensaje, veo como el bot ha detectado la actualización de 3 contenedores, entre ellos él mismo.
Para hacer la comprobación de la actualización se baja la imagen más nueva y compara el hash sha:256 de la actual con la descargada. Si es diferente alerta de la posible actualización.

En la versión 1.0.0, esta imagen nueva NO se borraba, lo que efectivamente daba lugar a ese tipo de confusiones, puesto que no se ha actualizado realmente. Coexistían 2 imágenes del donde la recién descargada y última no estaba en uso.

Otro bug de la primera versión es que si no encontraba el tag siempre bajaba la latest. Ahora ya sí debe comparar cada hash con el de su tag específico.

Todo esto ha sido solucionado en la versión 1.1.0. Ahora sí elimina las imágenes que descarga para comprobar actualizaciones y también borra la imagen antigua al actualizar siempre y cuando no la esté usando otro contenedor.

En cuanto a los errores de python aparecen como TimeOut (definido en 60s). Pareciera que hubo un corte de red, lo cual no detiene el bot. No son errores preocupantes ni hacen que el bot se cierre.

Desconozco si más allá de lo explicado has notado algo más.

Para futuros comentarios agradecería mucho si especificas la versión en la que te encuentras (no el tag) sino viendo la salida de /version

Muchas gracias de nuevo.
