### ISSUE TITLE
Pause notifications

### ISSUE THREAD

**Issue by xorguy** [dgongut/docker-controller-bot#30]
Hi.

Because of performing multiples operations over containers the bot keeps notifying every start and stop for and can be a bit noisy. An idea, if feasible, would be to add a command to pause that kind of notifications for a specified amount of time.

I know I can stop the bot but sometimes you may be away and is a bit more complicated.  

Just an idea.

Thanks.

**Comment by dgongut** [comment]
It's a very good idea! I will try to think of a way to do this 👍

**Comment by dgongut** [comment]
Launched in v2.4.0 🚀
