### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by fernandeusto** [dgongut/docker-controller-bot#32]
Since version 2.3.0, docker-controler-bot consumes excessive CPU resources around 15% of CPU when idle. Even disabling the update check, as soon as is started it, the consumption remains between 15% and 20% only for this docker.

In versions 2.2.4 and lower, idle consumption is between 0% and 1%

It only occurs in some conditions. I have tried with the same docker compose on another computer with the same hardware and this problem does not occur.

![imagen](https://github.com/dgongut/docker-controller-bot/assets/87156183/a5e87b26-4995-420c-b693-5eef7e5bed5d)

![imagen](https://github.com/dgongut/docker-controller-bot/assets/87156183/271f0afe-520b-4009-bb7c-88af405b2d3b)

![imagen](https://github.com/dgongut/docker-controller-bot/assets/87156183/579f4b14-85f9-4a89-887a-989c8da88614)
![imagen](https://github.com/dgongut/docker-controller-bot/assets/87156183/903e90db-2c6e-4d1b-9d13-a5e3e5e6bd36)

Hardware: Nas Synology DS720+ (10gb RAM) with last DSM 7.2.1.69057 Update 5 and INTEL Celeron J4125

**Comment by dgongut** [comment]
Under study, but unable to reproduce. Some feedbacks with the same Synology Server and 920+ (same CPU) from other users do not corroborate the same behaviour.

**Comment by fernandeusto** [comment]
Solved with 2.5.1

![imagen](https://github.com/dgongut/docker-controller-bot/assets/87156183/694f1b28-2262-4866-86a3-0e1255bd7c79)
