### ISSUE TITLE
Change behaibour of command /checkupdate

### ISSUE THREAD

**Issue by Antroxin** [dgongut/docker-controller-bot#33]
First of all, thank you for the bot and the good work made.

When /checkupdate command is selected, it offers the list of installed dockers so user has to press the docker to update but there is no info about what dockers have a new version avaiable.

My sugestion is to add some mark or colour to notice that a new version is available to update the docker in the list.

**Comment by dgongut** [comment]
Hello! 

In fact right now you can find out if a container needs an update from the /list command. You'll see a ⬆️ emoji.
(Not in the buttons)

To perform the update you can do it from /checkupdate and from /info.

Regards

**Comment by dgongut** [comment]
Finally I will change the status icons for :heavy_check_mark: and :arrow_up: icon in this command.

**Comment by dgongut** [comment]
Launched in v2.4.0 🚀
