### ISSUE TITLE
Mapear otros Servidores

### ISSUE THREAD

**Issue by Antjrobles** [dgongut/docker-controller-bot#34]
Buenas, ¿Seria posible añadir de alguna manera otros servidores locales para poder mapear los contenedores de ese servidor?. Es decir, si tengo varias ips locales con contenedores, se podrían añadir al docker-compose?. Ya sea a través de la API de Docker o mapeando de alguna forma /var/run/docker.sock en esas direcciones. 
Gracias

**Comment by dgongut** [comment]
Buenas!

Por el momento no se contempla la posibilidad de controlar servidores remotos.

Docker-Controller-Bot es un contenedor docker más y está preparado y pensado para instalar un bot por servidor. Luego en Telegram puedes meterlos en un grupo para controlarlos todos desde el mismo servidor.

Si en un futuro se decide abordar se reabrira esta Issue :+1:
