### ISSUE TITLE
error phyton3 unraid despues de actualizar docker

### ISSUE THREAD

**Issue by Lito2022** [dgongut/docker-controller-bot#35]
he actualizado en unraid el docker y me da el siguiente error

alguna sugerencia??
Muchas gracias y enhorabuena por el curro que llevas dgongut

a ver si podemos solucionar esto, GRACIAS!

<img width="391" alt="error docker" src="https://github.com/dgongut/docker-controller-bot/assets/99551109/57f753d8-0341-422e-b0ec-fbc12ec8b458">

**Comment by gilberth** [comment]
No solo en unraid
![image](https://github.com/dgongut/docker-controller-bot/assets/847492/53a46e3c-7dca-4168-b193-dfd3a848fe99)

**Comment by Lito2022** [comment]
> No solo en unraid ![image](https://private-user-images.githubusercontent.com/847492/332188730-53a46e3c-7dca-4168-b193-dfd3a848fe99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMzczMjQsIm5iZiI6MTcxNjIzNzAyNCwicGF0aCI6Ii84NDc0OTIvMzMyMTg4NzMwLTUzYTQ2ZTNjLTdkY2EtNDE2OC1iMTkzLWRmZDNhODQ4ZmU5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQyMDMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTEyZTVmZDdiNDQwMzE0MWUzODlkNDBmNTQ2ZDc0MGU1YmQ1YzVjNDYzZTUzZGU3NTU1ZTFhMmM0NWIyOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KpCqW6o2uDnLCFAZUdSgdbEKww3rQ9rp2DyL30pg3iI)

supongo que haciendo rollback volvemos a la  anterior, pero no recuerdo como hacerlo.

**Comment by gilberth** [comment]
Cambié a la version [2.3.1] y ya no muestra el errro, el cambio que hice:

de " image: dgongut/docker-controller-bot:latest" a " image: dgongut/docker-controller-bot:2.3.1" en el docker-compose

**Comment by Lito2022** [comment]
genial, puse la 2.3.3 y funciona perfectamente, GRACIAS!

**Comment by Lito2022** [comment]
> Ayer ocurrió un problema con la actualización, dejando sin soporte algunas arquitecturas, mis disculpas por ello.
> 
> Ya debería estar solucionado. Pero me temo que por ejemplo en Synology, para que detecte de nuevo que la etiqueta latest tiene la arquitectura del procesador hay que borrar el proyecto de Container Manager y volver a crearlo.
> 
> El tag que se subió ayer 2.4.0 incluye los cambios de la latest, por si os falla y queréis poner la última versión.
> 
> De los errores se aprende y de este aprendo bastante, no creo que vuelva a pasar.
> 
> Para cambiar la versión del bot, es tan sencillo como en el docker-compose.yaml especificar con dos puntos la versión que se quiere;
> 
> dgongut/docker-controller-bot:2.4.0 dgongut/docker-controller-bot:latest ...

1000 gracias crack!!, luego actualizo!!!
