### ISSUE TITLE
¿ 1 giga para un bot ?

### ISSUE THREAD

**Issue by yeraycito** [dgongut/docker-controller-bot#39]
Pues eso, la versión 2.4.0 pasa a ocupar 1 giga y me sorprende mucho el aumento tan brutal de ese tamaño preguntándome si eso es normal o no.

<img width="879" alt="Captura" src="https://github.com/dgongut/docker-controller-bot/assets/65027248/acf46e04-a3d3-4e30-9079-68a406a4a60c">

**Comment by yeraycito** [comment]
Vale, el amigo PepeBetis me ha informado que ha habido problemas con el código.

**Comment by dgongut** [comment]
Efectivamente, es tema de los problemas que tuve para el despliegue. Lleva alguna que otra basura que en la próxima versión trataré de ponerla a dieta 😄

Disculpad las molestias 👍🏻

**Comment by dgongut** [comment]
Corregido en v2.5.0
