### ISSUE TITLE
Autoupdate with docker compose

### ISSUE THREAD

**Issue by sergius02** [dgongut/docker-controller-bot#42]
Hi! All my containers are created using `docker-compose.yml`, and I'm not sure how to add the auto-update label.

I tried this:
```yml
labels:
      - "DCB-Auto-Update"
```
```yml
labels:
      DCB-Auto-Update: 1
```
```yml
labels:
      DCB-Auto-Update: "1"
```
None of them seems to work

**Comment by dgongut** [comment]
It should be like first one 1️⃣ 


Example: 

`services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    labels:
      - "DCB-Ignore-Status"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=example
    labels:
      - "DCB-Auto-Update"`

**Comment by sergius02** [comment]
Oh! I tried again with the first option and... yes, it works!

Maybe I had some mistake, in any case it's solved, thanks for this great bot!
