### ISSUE TITLE
[Language Add (German)]

### ISSUE THREAD

**Issue by shedowe19** [dgongut/docker-controller-bot#47]
[de.json](https://github.com/user-attachments/files/16573550/de.json)

**Comment by shedowe19** [comment]
[de.json](https://github.com/user-attachments/files/16573565/de.json)
Update de.json

Volumes Header Corrected

**Comment by dgongut** [comment]
Wow! Thank you! I will check that this is correct and it will be added in the next version.

In the future, to add more, I will use Deepl translator but possibly they will not be correct, feel free to comment on an Issue for modification.

**Comment by dgongut** [comment]
Added in 3.2.0! Thanks!
