### ISSUE TITLE
Al actualizar un contenedor lo elimina de los stack de Portainer

### ISSUE THREAD

**Issue by Millan757** [dgongut/docker-controller-bot#5]
Tal y como dice el titulo, cuando actualizo un contenedor desde el bot, si este contenedor formaba parte de un stack creado desde Portainer, el nuevo docker (actualizado) desaparece del stack, pasa a ser un contenedor normal. 

El contenedor funciona perfectamente, utiliza la misma red que el stack, conserva las variables.... pero deja de pertenecer al stack, por lo que si yo quiero actualizar el docker-compose y recrear los dockers... me da error por que no puede borrar los dockers por no estar en el stack ni tampoco los puede crear por que ya existe un docker con el mismo nombre.

PD: Felicidades por el gran trabajo.

**Comment by dgongut** [comment]
Buenas, en primer lugar muchas gracias por el apoyo 😃.

Lamentablemente, los posibles errores que puedan surgir con programas de terceros no están dentro del foco de este proyecto. 

Es físicamente imposible tener en cuenta las particularidades de cada sistema operativo y/o programa.

La idea del proyecto es que no se intercomunique nada más que con el socket de Docker (docker.sock). Nada de almacenar datos ni tratar de manera especial a X o Y programa/OS 👍🏻.

Saludos.
