### ISSUE TITLE
Cómo configurar TELEGRAM_GROUP

### ISSUE THREAD

**Issue by SMSegura** [dgongut/docker-controller-bot#51]
Hola y gracias por su trabajo.

Trato configurar el TELEGRAM_GROUP para que se reciban las respuestas en dicho grupo (formado solo por administradores) y no consigo que reconozca el grupo, solo me responde si en TELEGRAM_GROUP pongo a alguno de los TELEGRAM_ADMIN

He sacado el TELEGRAM_GROUP siguiendo muchos de los bots que hacen esa función, No sé sí habrá alguno en particular que deba usar.

¿ Qué pudo estar haciendo mal ?

Saludos.

**Comment by dgongut** [comment]
Hola, gracias por exponer tu duda,

El bot funciona usando el chatID (un valor numérico) del grupo como bien dices, pero con un par de apuntes:

- El bot debe ser administrador de ese grupo
- Debe ser un grupo o un súper grupo como tal, **no puede ser un canal**

Un último apunte es que cuando se añaden bots como administrador a un grupo existe la posibilidad de que el chatID del grupo cambie. No es cosa del bot, es del funcionamiento de Telegram por seguridad y está recogido en su documentación. Por lo que aconsejaría cerciorarse de que el chatID que estás poniendo sigue siendo el del grupo.

El bot siempre escribe en los logs por dónde está recibiendo mensajes, por lo que de ahí podrás obtener exactamente cuál es el ChatID del grupo desde el que le estás escribiendo. Un ejemplo:

```
2024-10-23 14:45:41 - DEBUG: COMMAND: /start@*****
2024-10-23 14:45:41 - DEBUG: USER: 44*****
2024-10-23 14:45:41 - DEBUG: CHAT/GROUP: -100192**********
2024-10-23 14:45:41 - DEBUG: THREAD ID: 1
```

Si te quedan dudas puedes continuar por esta vía o contactarme por Telegram a @dgongut, encantado de ayudar por esta o por otra vía más directa.

Saludos

**Comment by SMSegura** [comment]
Gracias por su respuesta.

Me faltaba añadir el propio bot al grupo.

Muy buen trabajo.

Saludos

**Comment by dgongut** [comment]
¡Me alegro de que lo hayas solucionado! Es mucho más habitual de lo que parece que sucedan esas cosas jeje.

¡Un saludo y gracias por usarlo!
