### ISSUE TITLE
After muting the bot messages about available updates keep coming

### ISSUE THREAD

**Issue by xorguy** [dgongut/docker-controller-bot#55]
Hi.

The bot started to send messages about updates available for some of my Docker containers and because I knew there would be few more messages I muted it for 10 minutes, but the messages about updates kept coming.
I expected that if the bot is muted then no messages at all are sent.

**Comment by dgongut** [comment]
Hello!

Since the check update interval is usually very large I didn't fall into this hehe

It could be a nice addition, so I will add it in the very next update.

**Comment by dgongut** [comment]
Solved in 3.5.0
