### ISSUE TITLE
Request for an option to only send messages for updates available for current running containers

### ISSUE THREAD

**Issue by xorguy** [dgongut/docker-controller-bot#56]
Hi.
I think it can help people who have docker containers created but not running to prevent spamming with multiple messages of available updates for dockers that are not currently running, maybe this can be set as a variable so user can choose from.

Thanks.

**Comment by dgongut** [comment]
Hello,

At first I denied doing that, but I see that it is a recurring request.

It will be added in the next version.

**Comment by dgongut** [comment]
Solved in 3.5.0
