### ISSUE TITLE
Improve local development and bug solving of application

### ISSUE THREAD

**Issue by esdedev** [dgongut/docker-controller-bot#57]
First of all, congratulations for the project, it is super useful. I encourage everyone who can to contribute to it.

While researching to fix some bug in **issues**, I was wondering how to improve the local development of the container. So as not to have to delete the image and recreate it at each change to the file. For this I have proposed:
- To use locally the volume of the entire docker folder in /app. Add to the .gitignore file the new files to ignore.
- Create a requirements.txt file to avoid having to modify the Docker file every time you want to add a dependency.
- Install nodemon so that every time we modify the docker-controller-bot.py file locally, we do **hot reload** of it. And run it in the entrypoint of the Dockerfile file.

Attached Pull request.

![image](https://github.com/user-attachments/assets/98b6388d-2465-44e7-b96a-9652ca623c97)

**Comment by dgongut** [comment]
Sure! I will test it and made some modifications. Thanks for contributing!
