### ISSUE TITLE
Curiosidades

### ISSUE THREAD

**Issue by yeraycito** [dgongut/docker-controller-bot#6]
Acabo de reinstalar el docker lógicamente con la última versión 1.2.0 por motivos personales sin importancia y mirando el log he visto esto:

![1](https://github.com/dgongut/docker-controller-bot/assets/65027248/7d683ca6-ff83-4ba1-aadb-804ac7078837)

El docker busca un contenedor UPDATER - Docker - Controler - Bot y no lo encuentra, a pesar de eso el docker funciona a la perfección. De hecho una vez instalado me ha notificado al bot de Telegram una nueva actualización de uno de mis contenedores y desde el bot lo he actualizado sin ningún problema.

![2](https://github.com/dgongut/docker-controller-bot/assets/65027248/120b968c-3891-4713-9f2e-0a6b82cb8100)

Otra curiosidad que me ha llamado la atención es la siguiente, tengo tu docker instalado desde el primer dia que lo publicaste y a dia de hoy en el docker compose publicado aquí ha desaparecido una variable que si tenía en su primera versión que es esta:

network_mode: host

En mi caso sigo manteniendo esa variable y el contenedor funciona, como digo, sin ningún problema.

**Comment by dgongut** [comment]
¡Muy buenas!

Qué buen ojo tienes jeje no se te escapa una ❤️ , te cuento;
En cuanto a la búsqueda del contenedor `UPDATER-Docker-Controller-Bot` es una funcionalidad que solo se usará tras su autoactualización. Esto es debido a que para hacer posible su propia actualización, el bot generará un contenedor docker temporal llamado de esa manera encargado de actualizar el bot desde fuera.

Tras su uso, ya no será necesario (ni siquiera para actualizar otros contenedores), por lo que se elimina cuando el bot arranca desde parado. En caso de encontrar ese contenedor, será porque ha sido autoactualizado. Entonces, el bot, como primera misión tendrá eliminar el contenedor `UPDATER-Docker-Controller-Bot` así como su imagen que quedaría sin usar.

En cuanto al segundo punto tienes razón, faltaba por actualizar el docker-compose.yaml de ejemplo en GitHub. Actualizado 👍
