### ISSUE TITLE
Petición imaginativa y complicada

### ISSUE THREAD

**Issue by yeraycito** [dgongut/docker-controller-bot#7]
En un grupo de Telegram de Qnap al que pertenezco hemos comentado hoy que por seguridad no hay necesidad de que algunos de los contenedores estén operativos a todas horas y estaría bien encontrar un método basado en algún tipo de Cron que los activara y desactivara a voluntad. En el caso de los nas de Synology parece que no es demasiado complicado realizarlo:

https://mariushosting.com/synology-schedule-start-stop-for-docker-containers/

Sin embargo en el caso de los nas de Qnap la cosa se complica y mucho. En el caso de su implementación en Docker " a secas " parece que también se puede conseguir:

https://www.howtogeek.com/devops/how-to-use-cron-with-your-docker-containers/

Explicado todo esto la petición " es sencilla " y consistiría en ver si fuera posible conseguir algún tipo de programación horaria de los contenedores a través de tu bot, gracias.

**Comment by yeraycito** [comment]
Por si te sirviera de ayuda:

https://github.com/mcuadros/ofelia

https://devcodelight.com/automatizar-tareas-con-cron-desde-docker-con-ofelia/

**Comment by dgongut** [comment]
Agradezco sinceramente tu propuesta de mejorar el bot. Es genial ver el interés en que siga avanzando el bot y me enorgullece mucho.

Después de analizar cuidadosamente la propuesta, he llegado a la conclusión de que, en este momento, no creo que sea la mejor opción implementar estos cambios tan significativos en el programa. Permíteme explicarte un poco mi perspectiva:

En primer lugar, el bot actualmente está diseñado para dar respuestas instantáneas y acciones rápidas. La idea de realizar modificaciones que impliquen estar pendiente de una programación no se alinea completamente con mis objetivos inmediatos para este bot.

Además, no me gustaría el hecho de ponerle a este bot una BBDD o un fichero de texto donde guardar dicha programación, ya que Ofelia, por ejemplo, al hacerlo por labels se ve muy limitado sin posibilidad de realizar diversas programaciones para un mismo contenedor.

No obstante, quiero dejar en claro que encuentro tu propuesta muy interesante y valiosa. No descarto la posibilidad de reconsiderar esto en el futuro, especialmente si el bot evoluciona a un estado muy maduro o si identifico alguna forma de hacerlo que no conlleve persistencia de datos y me de la flexibilidad que busco.

¡Gracias de nuevo por tu sugerencia y por tu continuo compromiso con el bot!

Un gran saludo!
